### ISSUE TITLE
implement a python script "create_sidecar_files"

### ISSUE THREAD

**Issue by robertoostenveld** [robertoostenveld/bids#1]
This should loop over all levels of
```
dataset/subj-xxx/ses-xxx/datatype
```
and should create sidecar json+tsv documents at the level of the dataset (subjects.tsv), the level of the subjects (sessions.tsv) and at the level of the sessions (dependent on whether it contains *.nii or *.ds datafiles)

**Comment by robertoostenveld** [comment]
The level "ses-xxx" is optional.

The datatype can be something like anat, dwi, func, fmap, beh, meg, eeg. It is optional.

**Comment by robertoostenveld** [comment]
@schoffelen, I created a first version. It just loops over directories, does not create any files yet. Can you look at the interface and help?

**Comment by schoffelen** [comment]
will do, perhaps later today, otherwise tomorrow.

**Comment by schoffelen** [comment]
Hier spuit 11: looks good so far, as far as I can tell

**Comment by robertoostenveld** [comment]
the script exists now, although still needs improvements.
